[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
